version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "maintenance"
      - "dependencies"
    versioning-strategy: increase-if-necessary
    groups:
      doc-deps:
        patterns:
        - "*sphinx*"
        - "numpydoc"
        - "jupytext"
        - "ipykernel"
        - "enum-tools"
      dev-deps:
        patterns:
        - "pytest*"
        - "mypy"
        - "requests-mock"
        - "pre-commit"
        - "ansys-grantami-recordlists"
      src-deps:
        patterns:
        - "ansys-openapi-common"
        - "requests*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       actions:
          patterns:
            - "*"
